### ISSUE TITLE
Installation requires license purchase

### ISSUE THREAD

**Issue by OvermindDL1** [vultix/intellij-ron-plugin#2]
This plugin isn't working as attempting to install it states that I need to purchase a license...?  o.O

$39/yr for individuals apparently...

It's even listed as such on the plugin page:  https://plugins.jetbrains.com/plugin/12635-ron-rusty-object-notation-/pricing#edition=personal

**Comment by vultix** [comment]
This is as intended.  Feel free to try the plugin out for a 30 day trial, but then to continue using the plugin will require a license.

**Comment by OvermindDL1** [comment]
How do you acquire a license then, unable to use any listed payment options.

**Comment by vultix** [comment]
To purchase a license go to the plugin page: (https://plugins.jetbrains.com/plugin/12635-ron-rusty-object-notation-/pricing#edition=personal)[https://plugins.jetbrains.com/plugin/12635-ron-rusty-object-notation-/pricing#edition=personal]

![image](https://user-images.githubusercontent.com/5114062/60521159-f4130400-9ca3-11e9-923d-36b040956ee0.png)
There are buy buttons under the monthly and yearly subscription options.  

Clicking either of those should take you to a page asking for your email address so JetBrains can send you the license.  

Check to ensure you accept the JetBrains agreement, then click "CONTINUE AS NEW CUSTOMER" to continue to the payment forms.

Let me know if you have any further issues.

**Comment by OvermindDL1** [comment]
Yes, I already have an account (I'm a teacher+IT at a low-income college so I have intellij ultimate that I use to teach with free from jetbrains), however even $4/month is ~20 meals, which is already a lot of money here and I'm not seeing any alternative payment options there other than credit cards or paypal, which neither is useful.  I'm happy to pay with what I can but it's not giving me the ability 'to' pay.  $4 once would make more sense for a configuration file plugin for an individual I'd think, but $4 every month seems quite a bit steep for something that would be used maybe twice a month...

**Comment by vultix** [comment]
As a teacher you should be able to get a license to the plugin for free, although I am unsure how.  I will reach out to JetBrains to try and find out and will respond back when I find out.

**Comment by OvermindDL1** [comment]
> As a teacher you should be able to get a license to the plugin for free, although I am unsure how. I will reach out to JetBrains to try and find out and will respond back when I find out.

That would be awesome, I thought the teacher/student packages were only for JetBrains products themselves and not any third-party products so that would be nice if otherwise.  ^.^

I'm unsure how it would work, but jetbrains should really use pricing dependent on location, $4 is a lot here, could feed someone for over a week if not two, though I'm guessing that's less than the price of a starbucks drink or so in fancier areas (we keep hearing that we are going to get a starbucks but it never pans out, probably because it wouldn't be able to stay in business here, nearest one is about 2-3 hours away).  No doubt people would game that though...

**Comment by vultix** [comment]
@OvermindDL1 There is not currently a way for teachers to get a plugin license for free, but I can manually do it for you through JetBrains if you send me your JetBrains email address.  

If you would rather not share your email here feel free to send it via email to me at [intellij.ron@gmail.com](mailto:intellij.ron@gmail.com)

**Comment by OvermindDL1** [comment]
Eh I'm not really one to be special cased, if it's not something I could get students to use with equal ease it's not really worth having.  This is great documentation though, and thanks for finding out!  :-)

**Comment by vultix** [comment]
I'm sorry I couldn't be of more help.  JetBrains is working on getting free plugins for all teachers and students, so hopefully there won't be too long of a wait.  Let me know if there is anything else I can do.
