### ISSUE TITLE
Auto-import produces IDE fatal error

### ISSUE THREAD

**Issue by alex5nader** [vultix/intellij-ron-plugin#3]
When using auto-import to import from either an external crate or local crate, I recieve an IDE fatal error and the type is not imported.

I am on Windows 10 and using CLion 2019.2.

Stack trace [here](https://gist.github.com/alex5nader/8be53ec81a92a0dbf9538735c74a263f).

**Comment by vultix** [comment]
Thank you for letting us know about the issue.  

We have found a fix and it is in the process of being released right now.  See [here](https://vultix.github.io/intellij-ron-plugin/changelog#v2019.02.01) for more details on the release.

The release has been published to JetBrains, but it may take up to 24 hours before it is available for download.  Please let us know if you continue to have issues afterwards!
